[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
on_chain_calculator = "ARmiAGe6oAEq5BKguHydD3zt2n5PkV2Q5PLA1McuMkJT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
